/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
       public Restaurant test = new Restaurant("The first",3,"$");
    @Test public void testRestaurantToString() {
        String output = test.toString();
        String expected = "Restaurant{name='The first', numOfStars=3, priceCategory='$', review=null}";
        assertEquals(expected,output);
    }

    @Test public void testReviewToString() {
        Review rev = new Review(this.test,"review 1","Mhd",5);
        String output = rev.toString();
        String expected = "Review{body='review 1', author='Mhd', numOfStars=5, restaurant=The first}";
        assertEquals(expected,output);
    }
    @Test public void testAddReview() {
        Review rev = new Review(this.test,"review 1","Mhd",5);
        test.addReview(rev);
        String output = test.toString();
        String expected = "Restaurant{name='The first', numOfStars=5, priceCategory='$', review=Review{body='review 1', author='Mhd', numOfStars=5, restaurant=The first}}";
        assertEquals(expected,output);
    }

    @Test public void testAddReviewEditStarsRating() {
        Review rev = new Review(this.test,"review 1","Mhd",5);
        int oldStars = test.getNumOfStars();
        int expectedOldStars =3;
        test.addReview(rev);
        int newStars = test.getNumOfStars();
        int expectedNewStars =5;
         assertEquals("old stars for the restaurant should be 3",expectedOldStars,oldStars);
         assertEquals("new stars for the restaurant should be 5",expectedNewStars,newStars);
    }



}
